### ISSUE TITLE
join us overlaps text

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/carpentries.org-DEPRECATED#2]
On about page I see this: 

![screen shot 2018-01-18 at 4 11 01 pm](https://user-images.githubusercontent.com/19176319/35128206-361849a4-fc6a-11e7-978b-d8159c625dec.png)

The join us bubble overlaps some of the text.

**Comment by weaverbel** [comment]
You are right - I did see that and meant to fix it. On it now. @ErinBecker

**Comment by weaverbel** [comment]
Fixed

**Comment by ErinBecker** [comment]
Wow! That was fast! Thanks @weaverbel.

**Comment by weaverbel** [comment]
I was already in there trying to find and fix stuff !
