### ISSUE TITLE
Code of Conduct link send to Software Carpentry website

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/carpentries.org-DEPRECATED#7]
"Our Code of Conduct" points to https://software-carpentry.org/conduct/ when it should point to https://carpentries.org/conduct/

**Comment by weaverbel** [comment]
Well it will point there once it is on but this site is a work in progress ! @rgaiacs I still have a ton of things to add.

**Comment by weaverbel** [comment]
This now points to the Carpentries Handbook which is correct.
